table_details:
  departments:
    table_name: "departments"
    schema: "practice"
    file_name: "../data/departments_fixed_width_file.txt"
    config_name: "../config/config.json"
    specification_name: "../data/col_specs_fwf_departments.json"