Table_Details:
  FIXED_WIDTH:
    Departments:
      table_name: "departments"
      schema: "practice"
      file_name: "../data/departments_fixed_width_file.txt"
      config_name: "../config/config.json"
      specification_name: "../data/col_specs_fwf_departments.json"

  COPY:
    Customers:
      table_name: "customers"
      schema: "practice"
      config_name: "../config/config.json"
      s3_file_path: "s3://sai-learn-airflow/data/customers.csv"
      ARN: "arn:aws:iam::413645087273:role/RS_S3"
      header_count: 1
      region: "us-east-1"
      delimiter: ","
      copy_command: "COPY {schema}.{table_name} FROM '{s3_file_path}' iam_role '{ARN}' delimiter '{delimiter}'
      IGNOREHEADER {header_count} region '{region}'"

  CREATE_EXTERNAL:
    Iris:
      ext_table_name: "iris"
      ext_schema: "ext_practice"
      config_name: "../config/config.json"
      database: "glue_s3"
      external_s3_file_path: "s3://sai-learn-airflow/data/iris.txt"
      ARN: "arn:aws:iam::413645087273:role/RS_S3"
      region: "us-east-1"
      create_external_schema_command: "create external schema {ext_schema} from data catalog database '{database}'
       region '{region}' iam_role '{ARN}'"
      create_external_table_command: "create external table {ext_schema}.{ext_table_name}( sepal_length decimal(8,2), sepal_width decimal(8,2), petal_length decimal(8,2), petal_width decimal(8,2), species varchar(255)) row format delimited fields terminated by ',' stored as textfile location '{external_s3_file_path}'"